/*//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class BinaryConversion
    {
        public static void BinaryNibbleSwap()
        {
            Console.WriteLine("Enter a Number To Swap");
            String Str = "";
            int SwapNumber = Util.userinputs();
            while (SwapNumber > 0)
            {
                int m = SwapNumber % 2; ;
                Str = Str + m;
                SwapNumber = SwapNumber / 2;
            }
            Console.WriteLine(Str);
            string Str2 = "";
            int[] arr = new int[10];
            for (int i = 0; i < arr.Length; i++)
            {
                Console.Write(arr[i]);
            }
            Char[] array = Str.ToCharArray();
            for (int i = array.Length; i > 0; i++)
            {
                Str2 = Str2 + array[i];
            }
            Str2 = "0" + Str2;
            Console.WriteLine(Str2);
            String first = "";
            String last = "";
            Char[] Chararr = Str2.ToCharArray();
            for (int i = 0; i < Chararr.Length; i++)
            {
                if (i < Chararr.Length / 2)
                {
                    first = first + Chararr[i];
                }
                else
                {
                    last = last + arr[i];
                }

            }
            string Numb = last = first;
            Console.WriteLine(Numb);
            int DecimalValue = int.Parse(Numb);
            Console.WriteLine(DecimalValue);

        }
    }
}
*/