//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class DecimalBinary
    {
        public static void ToBinary()
        {
            Console.WriteLine("Enter a Decimal Number");
            int DecNumber = Util.userinputs();
             int i;
            int[] ArrayNumber = new int[10];
            for( i=0;DecNumber >0 ;i++)
            {
               ArrayNumber [i] = DecNumber % 2;
                DecNumber = DecNumber / 2;
            }
           Console.WriteLine("The Converted Binary Number");
            for (i = i- 1; i >=0;i--)
            {
                Console.Write(ArrayNumber[i]+" ");
            }
        }
    }
}
