//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class Sqrt
    {
        public static void FindSquare()
        {
            Console.WriteLine("Enter a Number");
            double Number = Util.UserInput();
            double e = Math.E;
            double epsilon = 1.0*e-15;
            double t = Number;
            while(Math.Abs (t-Number/t)>epsilon*t)
            {
                t = (Number / t + t) / 2.0;
            }
            Console.WriteLine("Square root of " + Number + " is " + t);
        }
    }
}
