//<<auto-generated>>//
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    class StopWatch
    {
        int Hour1, Hour2, Minute1, Minute2, Seconds1, Seconds2,MilliSec1,MilliSec2;
        public  void Watch()
        {
           
            DateTime dt1 = DateTime.Now;
            DateTime dt = DateTime.Now;
            Console.WriteLine("Enter S for Start");
            string CharactertoStart = Console.ReadLine();
            if(CharactertoStart== "s")
            {
                Hour1 = dt1.Hour;
                Minute1 = dt1.Minute;
                Seconds1 = dt1.Second;
                MilliSec1 = dt1.Millisecond;
                Console.WriteLine("Enter Z for Stop");
                string CharactertoStop= Console.ReadLine();
                if (CharactertoStop == "z" )
                {
                    Hour2 = dt.Hour;
                    Minute2 = dt.Minute;
                    Seconds2 = dt.Second;
                    MilliSec2 = dt.Millisecond;

                }
            }
            Console.WriteLine((Hour2 - Hour1) + ":" + (Minute2 - Minute1) + ":" + (Seconds2 - Seconds1)+":"+(MilliSec2-MilliSec1));                                
        }
    }
}
