//<auto-generated/>
using System;

namespace FunctionalPrograms
{
    public class Harmonic
    {
        public static void HarmonicValue()
        {
            Console.WriteLine("Enter Harmonic Number");
            int Num = Util.userinputs();
            double HarmNum = 0;
            for(int i=1; i < Num; i++)
            {
                HarmNum += (double)1 / i;
                Console.WriteLine("Harmonic Number is " + HarmNum);
            }
            
        }
    }
}
