// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Sqrt.cs" company="Bridgelabz">
// Copyright © 2020  Company="BridgeLabz"
// </copyright>
// <creator name="Bandi Venu"/>
// --------------------------------------------------------------------------------------------------------------------

//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{/// <summary>
/// Square root Class 
/// </summary>
    class Sqrt
    {
        /// <summary>
        /// Method for finding Square root
        /// </summary>
        public static void FindSquare()
        {
            Console.WriteLine("Enter a Number");
            double Number = Util.UserInput();
            double e = Math.E;
            double epsilon = 1.0 * e - 15;
            double t = Number;
            while (Math.Abs(t - Number / t) > epsilon * t)
            {
                t = (Number / t + t) / 2.0;
            }
            Console.WriteLine("Square root of " + Number + " is " + t);
        }
    }
}
