// --------------------------------------------------------------------------------------------------------------------
// <copyright file="StopWatch.cs" company="Bridgelabz">
// Copyright © 2020  Company="BridgeLabz"
// </copyright>
// <creator name="Bandi Venu"/>
// --------------------------------------------------------------------------------------------------------------------

//<<auto-generated>>//
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalPrograms
{
    /// <summary>
    /// Stop Watch Class
    /// </summary>
    class StopWatch
    {
        int Hour1, Hour2, Minute1, Minute2, Seconds1, Seconds2,MilliSec1,MilliSec2;
        /// <summary>
        /// Method for Stop watch Display
        /// Watches this instance.
        /// </summary>
        public void Watch()
        {
           
            DateTime dt1 = DateTime.Now;
            DateTime dt = DateTime.Now;
            Console.WriteLine("Enter S for Start");
            string CharactertoStart = Console.ReadLine();
            if(CharactertoStart== "s")
            {
                Hour1 = dt1.Hour; //// For Hour 
                Minute1 = dt1.Minute; //// For Minutes
                Seconds1 = dt1.Second; //// For Secconds
                MilliSec1 = dt1.Millisecond; //// For MilliSeconds
                Console.WriteLine("Enter Z for Stop");
                string CharactertoStop= Console.ReadLine();
                if (CharactertoStop == "z" )
                {
                    Hour2 = dt.Hour;
                    Minute2 = dt.Minute;
                    Seconds2 = dt.Second;
                    MilliSec2 = dt.Millisecond;

                }
            }
            //// Printing the stop watch time
            Console.WriteLine((Hour2 - Hour1) + ":" + (Minute2 - Minute1) + ":" + (Seconds2 - Seconds1)+":"+(MilliSec2-MilliSec1));                                
        }
    }
}
